"""user_id_in_task

Revision ID: 69333a1ed202
Revises: 8c03f5d1ab61
Create Date: 2025-08-19 13:39:29.250605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69333a1ed202'
down_revision: Union[str, Sequence[str], None] = '8c03f5d1ab61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'Tasks', 'user_profile', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Tasks', type_='foreignkey')
    op.drop_column('Tasks', 'user_id')
    # ### end Alembic commands ###
