"""make_category_id_nullable

Revision ID: 72c34c1c3cb5
Revises: 0831abd6b305
Create Date: 2025-08-08 21:31:55.115040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c34c1c3cb5'
down_revision: Union[str, Sequence[str], None] = '0831abd6b305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'category_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'category_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
