"""user_init

Revision ID: 78640398d7dd
Revises: d1ac058a8aac
Create Date: 2025-08-14 23:28:31.128203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "78640398d7dd"
down_revision: Union[str, Sequence[str], None] = "d1ac058a8aac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profile",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("user_name", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("access_token", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("user_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profile")
    # ### end Alembic commands ###
