"""user_name-to-username

Revision ID: caf3ba486edf
Revises: 69333a1ed202
Create Date: 2025-09-27 15:14:08.576387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf3ba486edf'
down_revision: Union[str, Sequence[str], None] = '69333a1ed202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('user_profile', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('yandex_access_token', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_profile', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint(op.f('user_profile_user_name_key'), 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['username'])
    op.drop_column('user_profile', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('user_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_unique_constraint(op.f('user_profile_user_name_key'), 'user_profile', ['user_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_profile', 'name')
    op.drop_column('user_profile', 'email')
    op.drop_column('user_profile', 'yandex_access_token')
    op.drop_column('user_profile', 'google_access_token')
    op.drop_column('user_profile', 'username')
    # ### end Alembic commands ###
