"""removed_not_null_constraint

Revision ID: df3112de3b49
Revises: caf3ba486edf
Create Date: 2025-09-27 15:20:00.149270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df3112de3b49'
down_revision: Union[str, Sequence[str], None] = 'caf3ba486edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_profile', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_profile', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
